NetCoreActionResults/Models/ErrorViewModel.cs
namespace NetCoreActionResults.Models
{
  public class ErrorViewModel
  {
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
  }
}

NetCoreActionResults/Models/HomeViewModel.cs
namespace NetCoreActionResults.Models
{
  public class HomeViewModel
  {
    public PartialViewModel PartialModel { get; set; }

  }
}

NetCoreActionResults/Models/JsonViewModel.cs
namespace NetCoreActionResults.Models
{
  public class JsonViewModel
  {
    public bool IsSucceded { get; set; } = false;
    public string Message { get; set; }


  }
}

NetCoreActionResults/Models/PartialViewModel.cs
namespace NetCoreActionResults.Models
{
  public class PartialViewModel
  {
    private string _title = "partial";

    //public string Title { 
    //  get { return _title; } 
    //  set { _title =  value; } 
    //}

    /// <summary>
    /// initial değer ataması
    /// </summary>
    public string Title { get; set; } = "Partial";


    //public void SetTitle(string title)
    //{
    //  _title = title;
    //}

    //public string GetTitle()
    //{
    //  return _title;
    //}

   
  }
}

NetCoreActionResults/Models/TestViewModel.cs
namespace NetCoreActionResults.Models
{
  public class TestViewModel
  {
    public PartialViewModel PartialModel { get; set; } 
  }
}

NetCoreActionResults/Models/UserInputModel.cs
using System.Text.Json.Serialization;

namespace NetCoreActionResults.Models
{
  // JSONResult ile formdan veri post işlemi için kullanılacaktır.
  public class UserInputModel
  {


    public string UserName { get; set; }


    public string Email { get; set; }

  }
}

NetCoreActionResults/Models/UserViewModel.cs
namespace NetCoreActionResults.Models
{
  public class UserViewModel
  {
    public int Id { get; set; }
    public string Email { get; set; }
    public string UserName { get; set; }

  }
}

NetCoreActionResults/Models/ViewComponentViewModel.cs
namespace NetCoreActionResults.Models
{
  public class ViewComponentViewModel
  {
    public string Title { get; set; }

  }
}

NetCoreActionResults/Controllers/ActionResultsController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreActionResults.Models;

namespace NetCoreActionResults.Controllers
{
  public class ActionResultsController : Controller
  {
    /// <summary>
    /// string html static bir içeriği ekranda göstermek için kullanılan bir result
    /// </summary>
    /// <returns></returns>

    [HttpGet("html-result", Name = "htmlResultRoute")]
    public ContentResult HtmlContent()
    {
      //return new ContentResult()
      return Content("<p>Content Result</p>","text/html");
    }

    /// <summary>
    /// Partialview ise tanımlanmış olan bir html'i arayüzde bir parça halinde göstermek için kullanılır. partial view html içeriği kendi sayfasında üretilir.
    /// </summary>
    /// <returns></returns>
    [HttpGet("partial-result", Name ="partialResultRoute")]
    public PartialViewResult Partial()
    {
      var model = new PartialViewModel();

      //return PartialView("~/Views/Home/Partials/_TestPartial.cshtml", model);
      // shared klasörü altından klasör ismi view ismi şeklinde çağırabiliriz.
      return PartialView("Partials/_TestPartial",model);
    }

    /// <summary>
    /// ViewComponentler Shared Components klasörü altından çağırılırlar
    /// ViewComponentler partialview çok benzer fakat partialviewden daha bağımsız yapılardır.
    /// </summary>
    /// <returns></returns>

    [HttpGet("view-component-result", Name = "viewComponentResultRoute")]
    public ViewComponentResult ViewComponentResult()
    {
      return ViewComponent("Test");
    }

    [HttpGet("users", Name ="viewResultRoute")]
    public ViewResult Users()
    {
      var users = new List<UserViewModel>();
      users.Add(new UserViewModel { Id = 1, Email = "test1@test.com", UserName = "test1" });
      users.Add(new UserViewModel { Id = 2, Email = "test2@test.com", UserName = "test2" });
      users.Add(new UserViewModel { Id = 3, Email = "test3@test.com", UserName = "test3" });


      return View(users);
    }

    /// <summary>
    /// Uygulama AJAX gibi yapılar ile sayfa yenilenmeden javascript kodu ile arayüzde güncelleme yapmamız gereken durumlarda tercih edilen bir result tipidir. Uygula içinde yazılmış başka uygulamaların besleneceği bir servis gibi de kullanılabilir.
    /// like,comment,paylaş gibi arayüzde sayfa yenilenmeden yapılması gereken işlemler için tercih ederiz.
    /// json Resultların kendine ait bir view olmaz bir view içerisinde viewcomponent gibi veya partial gibi çağırılırlar. Tek değişiklik js olarak çağırılmalarıdır.
    /// AJAX için FromBody yazmayı unutmayalım !
    /// Fetch işlemlerinde post ederken FromBody attribute yazmamıza gerek yok.
    /// </summary>
    /// <returns></returns>
    /// 
    [HttpPost("json-result", Name ="jsonResultRoute")]
    public JsonResult JsonResult([FromBody] UserInputModel data)
    {

      // veri tabanı işlemleri kayıt update işlemleri

      var result = new JsonViewModel
      {
        IsSucceded = true,
        Message = "İşlem Başarılı"

      };


      return Json(result);
    }


    [HttpGet("file-result", Name ="fileResultRoute")]
    public FileResult FileResult()
    {
      return File("~/docs/NET-Microservices-Architecture-for-Containerized-NET-Applications.pdf","application/pdf");
    }

    [HttpGet("unauthorized-result", Name = "unAuthorizedResultRoute")]
    public UnauthorizedResult UnauthorizedResult()
    {
      return Unauthorized(); // 401 sayfası döndürür.
    }


    [HttpGet("notfound-result", Name = "notFoundResultRoute")]
    public NotFoundResult NotFoundResult()
    {
      // kaynak link bulunamadığı zaman döndüreceğimiz result tipi
      return NotFound();
    }



    [HttpGet("redirect-result", Name ="redirectResultRoute")]
    public RedirectResult RedirectResult()
    {
      //return RedirectToAction("Privacy","Home");
      
      return Redirect("/Home/Privacy");
    }

    [HttpGet("redirect-route-result", Name ="redirectRouteResultRoute")]
    public RedirectToRouteResult RedirectRouteResult()
    {
      return RedirectToRoute("htmlResultRoute");
    }



  }
}

NetCoreActionResults/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreActionResults.Models;
using System.Diagnostics;

namespace NetCoreActionResults.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
      _logger = logger;
    }

    public IActionResult Test()
    {
      var model = new TestViewModel();
      model.PartialModel = new PartialViewModel();

      return View(model);
    }
    // View döndürken eğer view içerisinde tanımlı bir partial varsa view modele partial modelleri eklememiz gerekecek. buda geliştirme yaparken bir sorun teşkil edecek.
    public IActionResult Index()
    {
      var model = new HomeViewModel();
      model.PartialModel = new PartialViewModel();

      return View(model);
    }

    public IActionResult Privacy()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

NetCoreActionResults/Views/Shared/Components/Test/TestViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreActionResults.Models;

namespace NetCoreActionResults.Views.Shared.Components.Test
{
  /// <summary>
  /// 1.Kural: view componentler viewcomponent kalıtım alır
  /// 2.Kural: view componentler içerisinde sadece 1 method bulunur ve adı InvokeAsync olarak tanımlanır
  /// 3.Kural: view componentler performans amaçlı async task formatında tanımlanır. asenkrondur.
  /// </summary>
  public class TestViewComponent:ViewComponent
  {
    // title değeri gönderek yada title parametresi boş geçilerek çağırabiliriz.
    public async Task<IViewComponentResult> InvokeAsync(string? title)
    {

      // ilgili db işlemleri vs yapılıp veri controller yerine bu method içerisinde çekilerek view model olarak gönderilir.
      // yani view'un ihtiyaç duyduğu model bu class olarak controller actiondan izole bir şekilde tanımlanır.

      var model = new ViewComponentViewModel();
      model.Title = title ?? "ViewComponent";
      // default html döndürür.
      // ?? işareti kendinden önce gelen değerin null olup olmamasını kontrol eder.
      // null ise ViewComponent string döner null değilse title parametresinin değeri döner.
      return View(model);
    }
  }
}

NetCoreActionResults/Views/ActionResults/Users.cshtml
@{
    ViewData["Title"] = "Users";
}

@model List<UserViewModel>

<h1>Users</h1>

<hr />

@*Javascipt ile form gönderme AJAX*@
<form id="frm" novalidate onsubmit="SendUserAjax(event)" method="post">
<label>Email</label>
<input id="emailInput" class="form-control" type="text" name="Email" />
<label>UserName</label>
<input id="usernameInput" class="form-control" type="text" name="UserName" />
<br />
<button type="submit" class="btn btn-success">JSON Ekle</button>

</form>
<br />
<ul id="liste" class="list-group">
  @foreach (var item in Model)
  {
    <li class="list-group-item">
      @item.UserName
    </li>
  }
</ul>

<br />
<button class="btn btn-primary" onclick="SendUser()">User Bilgilerini Post Et</button>

<!-- veri gönderme işleminde eğer contentType bilgisini berlirtmez isek json xml tipinde istek yaptığımız bilgisi bu durumda 415 hata kodu alırız. -->

@section Scripts {
  <script>

    function SendUserAjax(event){
        event.preventDefault(); // formun post edilmesini engelledik. post back olmayı engeller.

        console.log('event', event);

        const data = {
            //Email: $('#emailInput').val(),
            //UserName: $('#usernameInput').val()
        };
        // $ keyword ile Jquery kütüphanesine bağlandık. Jquery kütüphanesi üzerinden $.ajax ile json result ile çalışmış olduk.

        //console.log('frm',$(event).serializeArray());

        const formData = $('#frm').serializeArray();

        console.log('formData', formData);

        $.each(formData,(index,item) => {
            console.log('key', index);
            console.log('value', item);
            data[item.name] = item.value;
        })

        console.log('data', data);

        // AJAX ile post ederken action içindeki modelden önce bodyden gönderildiğini söylemek için [FromBody] yazalım.

        $.ajax({
          method:'POST',
          url:'/json-result',
          contentType:'application/json',
          data: JSON.stringify(data),
          success:(response) => {
            console.log('response', response);

            //$"{}"
                if (response.isSucceded) {
                  // backtick
                  $('#liste').append(`<li class='list-group-item'>${data.UserName}</li>`);
                    //$('#emailInput').val('');
                    //$('#usernameInput').val(''); // boş bırakalım
                    $('#frm').trigger('reset');
                }
          },
          error:(err) => {
            console.log('hata', err);
          }
        })
    }

    function SendUser(){
         var data = { UserName: 'ali', Email: 'test@test.com' };

         console.log('data', data);
    

    fetch('/json-result', { method:'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            data: JSON.stringify(data) })
    .then(response => {
      // isteğin başarılı sonuçlandığında çalışacak olan fuction
      console.log('response', response);

      return response.json(); // gönderilecek olan değeri json formatına dönüştür.

    })
    .then(data => {
      // json formatına dönüşmüş hali yakalanır. mvcden dönen mesajı yakalarız.
      console.log('data', data)

                alert(data.message)
    })
    .catch(function(err) {
      // istek hatalo olduğunda çalışacak function
            console.log('error', err);
    })
    }

    //function onError(error) {

    //}

  </script>
}

NetCoreActionResults/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@* View den partial çağırma yöntemi *@
@* Tag Helper yöntemi *@
<partial name="Partials/_TestPartial" model="Model.PartialModel" />
<hr />

@* Html helper yöntemi *@
@await Html.PartialAsync("Partials/_TestPartial", Model.PartialModel)

<hr />
@* View Component çalıştırma çağırma şeklimiz, aşağıdaki gibi componentin hiç bir model bağımlılığı yoktur. *@
@await Component.InvokeAsync("Test",new {title = "deneme1"});

NetCoreActionResults/Views/Home/Test.cshtml
@model TestViewModel

@{
    ViewData["Title"] = "Test";
}

<partial name="Partials/_TestPartial" model="Model.PartialModel" />




@await Component.InvokeAsync("Test")

<h1>Test</h1>

NetCoreActionResults/Views/Shared/Components/Test/Default.cshtml
@model ViewComponentViewModel


<p>
  @Model.Title
</p>

NetCoreActionResults/Views/Shared/Partials/_TestPartial.cshtml
@model PartialViewModel

<p>
  @Model.Title
</p>

@* partial klasörümüz views shared altında tanımlanır ve partial isimlendirmede _ ile başlamak yaygın bir kullanımdır. Partial viewlerin suffix son takısı Partial yazmak yaygın bir kullanımdır.  *@

NetCoreActionResults/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreActionResults</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetCoreActionResults.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCoreActionResults</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              Action Results
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li><a class="dropdown-item" asp-route="htmlResultRoute">Html Result</a></li>
              <li><a class="dropdown-item" asp-route="partialResultRoute">Partial Result</a></li>
              <li><a class="dropdown-item" asp-route="viewComponentResultRoute">View Component Result</a></li>
              <li><a class="dropdown-item" asp-route="viewResultRoute">View Result</a></li>

              <li><a class="dropdown-item" asp-route="fileResultRoute">File Result</a></li>

              <li><a class="dropdown-item" asp-route="unAuthorizedResultRoute">Unauthorized Result</a></li>

              <li><a class="dropdown-item" asp-route="notFoundResultRoute">NotFound Result</a></li>

              <li><a class="dropdown-item" asp-route="redirectResultRoute">Redirect Result</a></li>

              <li><a class="dropdown-item" asp-route="redirectRouteResultRoute">RedirectRoute Result</a></li>

          
            </ul>
          </div>



                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NetCoreActionResults - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

  <partial name="_ValidationScriptsPartial" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>